# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Xilinx/constraints.xdc

# XDC: new/constraints_v2.xdc

# IP: ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0 || ORIG_REF_NAME==gig_ethernet_pcs_pma_0} -quiet] -quiet

# IP: ip/clk_wiz_1/clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] -quiet
